language: python
cache: pip
sudo: false
python:
- "3.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
- pip install --upgrade pip setuptools
- pip install -e .
- pip install -r requirements.txt
- pip install -r dev-requirements.txt
# command to run tests, e.g. python setup.py test
env:
# Pushover user
- secure: "eKxRf8pUHoCOx1ror0VQuQ53BIR0fM0QeeYobANJjlKQNsnbY80VWilWN0Bn1532ObqynTlBUqlq8jJge4ho3emz01BBAvSDddg4/037EoP64vpNzEWxxorR8jop8rfDpbh3917Gqd8NzAOf8v4PkVJq+wB3c0DV/BE/SV6v5cdnsTa8GAJM6zQpj2Sg2kgGHoAaT37npD5q4zKTqpJT1WgAht9RJ3Od10aBT8QABz+wpUVLxg9FnthmznbgO9seeZhctTGuCSj1TAz/XQjJD8fS8XiEjhwAoTmJec58Zqk6pjhEnWV9L91Z9s4ICyN2+tnrjOSl5apo98nRZ8yappSwilLCjQ4VhlSdOCwLv/LjN2HT+XTQS/W068wuEtSkbLMoV2eE87wD86iiiIBMax9I5Kw69xYZk7kNQYzxlrBYk9lj3vlrI8YwXBnHdaIWyZlWgNSQy9vsk2ZIxSBLdeKj+z2DNBqJ3UMn636oncgPvphZBhmrbeSBS5jcc2hwdCGtcbWvRNKmKcP8xa02Nfv1zCTSW2T3IdI7XfTEX7WUwEMy1heuCgTXdm4XBT3Uemte4AOKVKgamT/6bchlo+tFBQSK6ot841GMPYftVNTjcLUlJYr5mUJkotRY6uQK/vvpBWI4eAWM58GwidG5Oi3whZiAGKl8Xv0M1SXlAuI="
# Pushover token
- secure: "i0/6+uzOG63I119PodRGXlB7edSIsNfQo5C9F/WGS45hVzdPCTfxn8pCzpd9lEaYQU5SGxp7ZdkjGfx0DjrQPxk5M352eLi1eWvEQn+S7628j//mZtYnfWk/716uKThfLP+zEU3Kl1swJyBkxYEUu0M2SUPvhFjEX7Ss7H416xgnmFX5omEScR8WrIoVACvbhgQoqWgnv4urRt+MmJh5D254lEU3TXnf1wc3o8J+ocg2pigQyExCYE0xxhQAq07Sjb1jHi0x0sfYRR2Ir5O5fsropm1ndDCtMk1eEMJUFSbvANkeqXet5XBNybb6FyfEDpQQ//ZDyKYouPZioWLjfYqw0Yq1yTKHLhnO732BoJBPQxTEt1ZnaA6/MJXK8ok18V/LTyIQuTbioMKHCkKumH1gZKCbTbITzX8hgdcEcCV1hANAR56Ew+gWjlj5EpupgB4mL7KLG83xPHQhVheuUc5tQv8QLCpEidpHX6iEktx+KAfzVIX7GS3vfvNzr3svfTEVOq3odgW09l1D5QXXzpjuNuGbiWeQkDiqrQp+niLPMXzC7Sv01AfwwybJ8DkYBwPbjmOMRXy7T/g683ERmHrVnbHnqWVdzBgrnPCHIzBxpu6G5AqQNqNtxTYWxALZr87W1bH6POUzKRXdYnJizpFqC615LcxiwipNlo+jCR0="
script: pytest --cov=./
after_success:
  codecov
